# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a69f33029713f794cbfbdccae716da03672577702c249480028204d61ce2483bb696decf4601a723b86f5f53ab20a728f15be6b8bc34385e5b366becaac7d97a

test:
  secret_key_base: 9867af988a6ef74bb9c79b03a466233f55915005082f03d0558f57146b97c95343ca59d22dde8e4d97fe95bbf0c6602735588edc480098ca5b8db2026f0f2531

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
